"""
Stress Testing Default Grids and Templates

Deterministic defaults for stress test parameter grids.
These values are NOT generated by LLM and provide consistent,
predefined ranges for sensitivity analysis.
"""

from typing import Dict, List, Any


# View magnitude multipliers
# Applied to view expected_outperformance or expected_return
# Example: If base view is +2%, standard grid tests: -4%, -2%, 0%, +2%, +4%
DEFAULT_VIEW_MULTIPLIERS: Dict[str, List[int]] = {
    "conservative": [-1, 0, 1],
    "standard": [-2, -1, 0, 1, 2],
    "aggressive": [-3, -2, -1, 0, 1, 2, 3]
}


# Confidence scaling factors
# Applied to view confidence values
# Example: If base confidence is 0.8, conservative grid tests: 0.48, 0.64, 0.8
DEFAULT_CONFIDENCE_GRID: Dict[str, List[float]] = {
    "conservative": [0.6, 0.8, 1.0],
    "standard": [0.4, 0.6, 0.8, 1.0],
    "aggressive": [0.2, 0.4, 0.6, 0.8, 1.0]
}


# Factor exposure scaling factors
# Applied to factor loadings in the factor model
# Example: Amplify or dampen a specific factor's influence
DEFAULT_FACTOR_SCALE: Dict[str, List[float]] = {
    "conservative": [0.5, 1.0, 1.5],
    "standard": [0.5, 1.0, 1.5, 2.0],
    "aggressive": [0.25, 0.5, 1.0, 1.5, 2.0, 3.0]
}


# Tau (uncertainty in prior) multipliers
# Tau controls the weight given to views vs prior
# Higher tau = more weight to views
DEFAULT_TAU_MULTIPLIER: Dict[str, List[float]] = {
    "conservative": [0.5, 1.0, 1.5],
    "standard": [0.5, 1.0, 2.0],
    "aggressive": [0.25, 0.5, 1.0, 2.0, 3.0]
}


# Volatility multipliers for covariance matrix scaling
# Used to stress test impact of changing market volatility regime
DEFAULT_VOLATILITY_MULTIPLIER: Dict[str, List[float]] = {
    "conservative": [0.8, 1.0, 1.2],
    "standard": [0.6, 0.8, 1.0, 1.2, 1.5],
    "aggressive": [0.5, 0.7, 1.0, 1.3, 1.6, 2.0]
}


# Predefined regime templates
# Each template defines multiple parameter adjustments simultaneously
# to simulate common market regimes
REGIME_LIBRARY: Dict[str, Dict[str, Any]] = {
    "high_uncertainty": {
        "description": "Market regime with elevated uncertainty and volatility",
        "tau_multiplier": 2.0,
        "confidence_scale": 0.7,
        "volatility_multiplier": 1.3
    },
    "risk_off": {
        "description": "Flight to safety, risk aversion increases",
        "risk_aversion_shift": 2.0,
        "volatility_multiplier": 1.4,
        "confidence_scale": 0.6
    },
    "risk_on": {
        "description": "Risk-seeking behavior, low volatility regime",
        "risk_aversion_shift": -1.0,
        "volatility_multiplier": 0.7,
        "confidence_scale": 0.9
    },
    "crisis": {
        "description": "Extreme market stress scenario",
        "tau_multiplier": 3.0,
        "confidence_scale": 0.4,
        "volatility_multiplier": 2.0,
        "risk_aversion_shift": 3.0
    },
    "low_vol": {
        "description": "Unusually calm market conditions",
        "volatility_multiplier": 0.6,
        "tau_multiplier": 0.8,
        "confidence_scale": 0.85
    }
}


def get_grid_for_stress_type(stress_type: str, grid_level: str = "standard") -> List[Any]:
    """
    Retrieve the appropriate default grid for a given stress type and level.
    
    Args:
        stress_type: Type of stress test
        grid_level: Intensity level (conservative, standard, aggressive)
        
    Returns:
        List of grid values for the specified stress type and level
        
    Raises:
        ValueError: If stress_type or grid_level is not recognized
    """
    grid_mappings = {
        "view_magnitude": DEFAULT_VIEW_MULTIPLIERS,
        "confidence_scale": DEFAULT_CONFIDENCE_GRID,
        "factor_amplification": DEFAULT_FACTOR_SCALE,
        "tau_shift": DEFAULT_TAU_MULTIPLIER,
        "volatility_multiplier": DEFAULT_VOLATILITY_MULTIPLIER
    }
    
    if stress_type not in grid_mappings:
        raise ValueError(
            f"Unknown stress_type: {stress_type}. "
            f"Must be one of: {list(grid_mappings.keys())}"
        )
    
    grid_dict = grid_mappings[stress_type]
    
    if grid_level not in grid_dict:
        raise ValueError(
            f"Unknown grid_level: {grid_level}. "
            f"Must be one of: {list(grid_dict.keys())}"
        )
    
    return grid_dict[grid_level]


def get_regime_template(template_name: str) -> Dict[str, Any]:
    """
    Retrieve a predefined regime template by name.
    
    Args:
        template_name: Name of the regime template
        
    Returns:
        Dictionary containing regime parameters
        
    Raises:
        ValueError: If template_name is not found in library
    """
    if template_name not in REGIME_LIBRARY:
        available = ", ".join(REGIME_LIBRARY.keys())
        raise ValueError(
            f"Unknown regime template: {template_name}. "
            f"Available templates: {available}"
        )
    
    return REGIME_LIBRARY[template_name]


def list_available_regimes() -> List[str]:
    """
    Get a list of all available regime template names.
    
    Returns:
        List of regime template names
    """
    return list(REGIME_LIBRARY.keys())
