"""
Simulated news fetching module.

The real NewsAPI is replaced by an LLM-based article generator so the
pipeline works without an external API key and without network reliability
issues.  The output format of fetch_news_for_stock is unchanged so every
caller (news_orchestrator, etc.) works without modification.
"""

from typing import Dict, List, Optional

from app.services.news_api.generate_news import generate_simulated_articles


def fetch_news_for_stock(
    ticker: str,
    limit: int = 5,
    keywords: Optional[List[str]] = None,
    # Legacy date params kept for API compatibility but no longer used
    from_date: Optional[str] = None,
    to_date: Optional[str] = None,
    sort_by: str = "publishedAt",
) -> List[Dict]:
    """
    Return simulated news articles for *ticker* generated by an LLM.

    Args:
        ticker:    Stock ticker symbol (e.g. 'AAPL')
        limit:     Number of articles to generate
        keywords:  Optional themes / keywords to weave into the articles
        from_date: Ignored (kept for backward compatibility)
        to_date:   Ignored (kept for backward compatibility)
        sort_by:   Ignored (kept for backward compatibility)

    Returns:
        List of article dicts: title, source, url, description,
        published_at, author, content
    """
    return generate_simulated_articles(ticker=ticker, keywords=keywords, limit=limit)


def fetch_news_for_multiple_stocks(
    tickers: List[str],
    limit_per_stock: int = 10,
    keywords: Optional[List[str]] = None,
    # Legacy date params kept for API compatibility
    from_date: Optional[str] = None,
    to_date: Optional[str] = None,
) -> Dict[str, List[Dict]]:
    """
    Generate simulated news for multiple stock tickers.

    Args:
        tickers:        List of stock ticker symbols
        limit_per_stock: Maximum articles per ticker
        keywords:       Optional themes to pass to the generator
        from_date:      Ignored (kept for backward compatibility)
        to_date:        Ignored (kept for backward compatibility)

    Returns:
        Dictionary mapping ticker -> list of articles
    """
    results = {}
    for ticker in tickers:
        print(f"Generating simulated news for {ticker}...")
        try:
            articles = fetch_news_for_stock(ticker, limit_per_stock, keywords=keywords)
            results[ticker] = articles
            print(f"  ✓ Generated {len(articles)} articles")
        except Exception as e:
            print(f"  ✗ Error generating news for {ticker}: {e}")
            results[ticker] = []
    return results
